### ISSUE TITLE
How are chain forks handled in subsquid for substrate?

### ISSUE THREAD

**Issue by sebastianmontero** [subsquid/squid-sdk#145]
Hi, not sure if this is the correct place to ask this questions, but I didn't find a discord community or telegram channel for subsquid, I'm starting to evaluate indexing solutions for substrate chains and I was looking into subsquid and didn't find an answer to 2 technical questions that I would like to clarify before picking a solution:
1.- How are chain forks handled?
2.- How are structural data changes overtime handled (runtime upgrades)?

Thanks

**Comment by eldargab** [comment]
Hi, @sebastianmontero !

>How are chain forks handled?

At the moment only finalised blocks are indexed, meaning the is no forks. 

Support for non-finalised blocks will be implemented in the near future and will be almost transparent for the end users.

We are going to track DML statements and write a log, that would allow us to rollback statements in case of a fork.

> How are structural data changes overtime handled (runtime upgrades)?

We always track the correct metadata to use to decode the particular block. 

There is one-to-one correspondence between the metadata and JSON structures mapping developers get in data handlers.

There are [tools](https://docs.subsquid.io/develop-a-squid/typegen/) to generate facade TypeScript classes, that assert that the data always has expected shape.

**Comment by sebastianmontero** [comment]
Hi @eldargab, thank you for the information, is there an ETA for the non-finalised blocks feature?

**Comment by eldargab** [comment]
ETA is around beginning or mid of the February.

**Comment by sebastianmontero** [comment]
Ok, thanks, and I don't know if you know this but what are the differences
between subsquid and subquery? when would you use one before the other?

**Comment by dzhelezov** [comment]
ArrowSquid now supports hot (unfinalized) blocks: https://docs.subsquid.io/basics/unfinalized-blocks/
ArrowSquid for Substrate will be released soon
