### ISSUE TITLE
Support for ink! v4 metadata decoding

### ISSUE THREAD

**Issue by XY-Wang** [subsquid/squid-sdk#149]
Hi,

We're currently working on adding decoded ink! contract events to our Substrate contracts explorer. The idea is that users will be able to upload source code or metadata to our [ink-verifier-server](https://github.com/web3labs/ink-verifier-server) and we use the generated/stored metadata in our squid to decode contract events.  Since we are mostly dealing with ink! v4 contracts, we'd like to know if `@subsquid/ink-abi` will support ink! v4 soon? I've recently opened an issue with the ink! team to check on `ink-v4-schema` updates. You can find the related issue here: https://github.com/paritytech/ink/issues/1564

**Comment by tmcgroul** [comment]
Hi @XY-Wang i was planning to delay v4 support until ink! team release new json schema.... But if there are users which are interested in this feature then i'll try to implement it this week

**Comment by XY-Wang** [comment]
That's amazing @tmcgroul ! 

In the ink! issue I have a [link](https://gist.github.com/XY-Wang/b54d3b4a14d12df7e273c5eece274682) to the v4 schema that I generated according to the ink! team's [documentation](https://github.com/paritytech/ink/tree/master/crates/metadata#metadata-schema-generation), perhaps it will be helpful for you? I believe that you'll have to remove `"format": "uri"` in the documentation portion for it to work with `ajv` though.

**Comment by tmcgroul** [comment]
> perhaps it will be helpful for you?

Thanks for it! I am going to use your schema

**Comment by tmcgroul** [comment]
@XY-Wang v4 support is available in a new version - `@subsquid/ink-typegen@0.1.0`

**Comment by XY-Wang** [comment]
Hey @tmcgroul, it works like a charm, thank you!

**Comment by tmcgroul** [comment]
@XY-Wang thank you too! You really helped for the release
