### ISSUE TITLE
ink! smart contract without events should have any type

### ISSUE THREAD

**Issue by vikiival** [subsquid/squid-sdk#151]
**Describe the bug**

I have a smart contract that does not emit any events
- https://github.com/swanky-dapps/marketplace/issues/9

the problem is when I do `npx squid-ink-typegen` (+ args ofc)

it generates content like:

```ts
export function decodeEvent(hex: string): Event {
    return _abi.decodeEvent(hex)
}

export type Event = never
```

Now it it impossible to build the squid 

```
src/abi/marketplace.ts:1412:5 - error TS2322: Type 'any' is not assignable to type 'never'.

1412     return _abi.decodeEvent(hex)
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/abi/marketplace.ts:1412
```

1. FIX is to return any if there is no event present 

```ts
export type Event = any
```

or
2. do not generate `decodeEvent` function

**Comment by belopash** [comment]
It looks correct to me. Why do you want to use this function if there are no events?

**Comment by belopash** [comment]
Maybe we should make it similar to evm-typegen, so there will be no such issues.
@tmcgroul what do you think?

**Comment by tmcgroul** [comment]
> Maybe we should make generated files similar to evm-typegen, so there will be no such issues. @tmcgroul what do you think?

Fixed just the type issue for now. I think there is no reason to make generated files similar to evm-typegen... but some features would be useful to implement
