### ISSUE TITLE
Unexpected behavior of queries that include `OR`

### ISSUE THREAD

**Issue by Lezek123** [subsquid/squid-sdk#153]
**To Reproduce**
1. Go to http://194.233.167.225:4350/graphql
2. Paste the query:
```graphql
{
  channels(where: {
    id_in: ["1", "2", "3"],
    OR: [
      { title_contains: "test" },
      { description_contains: "test"  }
    ]
  }) {
    id
  }
}
```
3. Hit the "Execute" button
4. Notice results including channels other than `1`, `2` and `3`

**Expected behavior**
The `OR` condition is joined with other conditions using the default operator (`AND`)

Expected difference in SQL:
```diff
SELECT "channel"."id" AS _c0 FROM "channel" AS "channel"
-  WHERE (("channel"."id" IN ($1, $2, $3)) OR (position($4 in "channel"."title") > 0) OR (position($5 in "channel"."description") > 0))
+  WHERE (("channel"."id" IN ($1, $2, $3)) AND ((position($4 in "channel"."title") > 0) OR (position($5 in "channel"."description") > 0)))
``` 

**Environment (please complete the following information):**
 - `@subsquid/graphql-server`: `3.2.3`

**Comment by eldargab** [comment]
Interesting, that both Hasura and Warthog behave the way you suggest, but I'm afraid it is too late to make breaking changes like this one...

**Comment by dzhelezov** [comment]
Closing as "Won't fix"
