### ISSUE TITLE
Error encountered with "wrapAccessError" message while decoding ABI for event with property "owner"

### ISSUE THREAD

**Issue by Cupnfish** [subsquid/squid-sdk#166]
**Describe the bug**
I encountered an error in my program named "wrapAccessError". The error message displayed "Error: deferred error during ABI decoding triggered accessing property "owner"". This error confuses me as the same event has been processed multiple times before, but this one failed.
**To Reproduce**

    Use the following data for testing:
    id: 0005648711-000174-018c3
    address: 0x314159265dd8dbb310642f98f50c066173c1259b
    data: 0x6330363834636235336331363831343865616130313363333864316330663339
    index: 174
    topics: ["0xce0457fe73731f824cc272376169235128c118b49d344817417c6d108d155e82","0x8352da3d0ebe15fd4bd7def280458b52cdb17c9c50ef26bed05f77a09a37033d","0x6630353636393265383962393531363132383865306565373939353535636238"]
    transactionIndex: 102

    Decode the data structure:
    [node: string, label: string, owner: string] & {
    node: string;
    label: string;
    owner: string;
    }

    The error "wrapAccessError" occurs with the message "Error: deferred error during ABI decoding triggered accessing property "owner""

**Expected behavior**
I expected the event to be processed successfully like the previous times.

**Screenshots**
N/A

**Comment by belopash** [comment]
Hello, we use ethersV5 for evm data decoding.
[Here](https://github.com/ethers-io/ethers.js/issues/891#issuecomment-932985011) dev says that error means that event has invalid UTF8 string.

**Comment by Cupnfish** [comment]
That seems to be the case, so how do I go about decoding the data? It seems to require a change in squid's internal code? @belopash

**Comment by belopash** [comment]
> That seems to be the case, so how do I go about decoding the data? It seems to require a change in squid's internal code? @belopash 

I think you can change type in abi from `string` to `bytes` and then manually convert it to utf8 string

**Comment by Cupnfish** [comment]
Here are the details of the error that occurred earlier:
```json
{"reason":"value out of range","code":"INVALID_ARGUMENT","argument":"value","value":20,"baseType":"address","name":"owner","type":"address","stack":"owner: value out of range (argument=\"value\", value=20, code=INVALID_ARGUMENT, version=bytes/5.7.0)\n    at Logger.makeError (/home/dev/ens-indexing/node_modules/@ethersproject/logger/lib/index.js:238:21)\n    at Logger.throwError (/home/dev/ens-indexing/node_modules/@ethersproject/logger/lib/index.js:247:20)\n    at Logger.throwArgumentError (/home/dev/ens-indexing/node_modules/@ethersproject/logger/lib/index.js:250:21)\n    at hexZeroPad (/home/dev/ens-indexing/node_modules/@ethersproject/bytes/lib/index.js:274:16)\n    at AddressCoder.decode (/home/dev/ens-indexing/node_modules/@ethersproject/abi/lib/coders/address.js:40:65)\n    at /home/dev/ens-indexing/node_modules/@ethersproject/abi/lib/coders/array.js:109:31\n    at Array.forEach (<anonymous>)\n    at unpack (/home/dev/ens-indexing/node_modules/@ethersproject/abi/lib/coders/array.js:88:12)\n    at TupleCoder.decode (/home/dev/ens-indexing/node_modules/@ethersproject/abi/lib/coders/tuple.js:74:60)\n    at AbiCoder.decode (/home/dev/ens-indexing/node_modules/@ethersproject/abi/lib/abi-coder.js:98:22)"}
```
I followed your suggestions to modify the ABI, but a new problem occurred. Due to changes in the types of the ABI, the topics of the ABI also changed. When calling decode later, an error occurred directly:
```shell
FATAL sqd:processor Error: fragment/topic mismatch (argument="topics[0]", expected="0xb2a780523c5674a736d3586a5bf0fc18b5ac3ebb741ed460a06589ac63b5899a", value="0xce0457fe73731f824cc272376169235128c118b49d344817417c6d108d155e82", code=INVALID_ARGUMENT, version=abi/5.7.0)
                                 at Logger.makeError (/home/dev/ens-indexing/node_modules/@ethersproject/logger/lib/index.js:238:21)
                                 at Logger.throwError (/home/dev/ens-indexing/node_modules/@ethersproject/logger/lib/index.js:247:20)
                                 at Interface.decodeEventLog (/home/dev/ens-indexing/node_modules/@ethersproject/abi/lib/interface.js:515:24)
                                 at LogEvent.decode (/home/dev/ens-indexing/lib/abi/abi.support.js:35:25)
                                 at handleNewOwnerOldRegistry (/home/dev/ens-indexing/lib/ensRegistry.js:146:47)
                                 at /home/dev/ens-indexing/lib/processor.js:187:75
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async TypeormDatabase.runTransaction (/home/dev/ens-indexing/node_modules/@subsquid/typeorm-store/lib/database.js:110:13)
                                 at async TypeormDatabase.transact (/home/dev/ens-indexing/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
                                 at async EvmBatchProcessor.process (/home/dev/ens-indexing/node_modules/@subsquid/evm-processor/lib/processor.js:302:17)
                                 reason: fragment/topic mismatch
                                 code: INVALID_ARGUMENT
                                 argument: topics[0]
                                 expected: 0xb2a780523c5674a736d3586a5bf0fc18b5ac3ebb741ed460a06589ac63b5899a
                                 value: 0xce0457fe73731f824cc272376169235128c118b49d344817417c6d108d155e82
```

**Comment by eldargab** [comment]
You can create a copy of event and modify its `topic[0]` before passing it to decode function.

**Comment by Cupnfish** [comment]
```typescript

export class LogEvent<Args> {
    private fragment: ethers.utils.EventFragment

    constructor(private abi: ethers.utils.Interface, public readonly topic: string) {
        this.fragment = abi.getEvent(topic)
    }

    decode(rec: LogRecord): Args {
        return this.abi.decodeEventLog(this.fragment, rec.data, rec.topics) as any as Args
    }
}

```
There is no way to change the value of the topic before passing the parameter in, it is readonly.

**Comment by belopash** [comment]
> There is no way to change the value of the topic before passing the parameter in, it is readonly.

@Cupnfish you can do 
```
if (log.topics[0] ==MyOldEvent.topic ) {
  log.topics[0] = MyNewEvent.topic
  ....
}
```

but if this errors heppens only one, you can just hardcode it

**Comment by Cupnfish** [comment]
Great! It solved my problem. This issue can be closed now! 🎉👍
