### ISSUE TITLE
How to fetch events from any contract?

### ISSUE THREAD

**Issue by zob360** [subsquid/squid-sdk#167]
Example: how to fetch Transfer events from every ERC20 from a chain without having to specify one contract.

I can reproduce this flow with the-graph but not with squid. Is there any example?
Thanks!

**Comment by hypnagonia** [comment]
you can track logs for Transfer event without specifying the contract

from official example, i think you remove topic2 here and get the desired result
```
const processor = new EvmBatchProcessor()
  .setDataSource({
    archive: 'https://eth.archive.subsquid.io'
  })
  .addLog([], {
    filter: [
      // topic0: 'Transfer(address,address,uint256)'
      [ '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' ],
      // topic1: anything goes
      [],
      // topic2: vitalik.eth
      [ '0x000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa96045' ]
    ],
    data: {
      evmLog: { id: true, data: true },
      transaction: { hash: true }
    } as const
  })
```

check the docs
https://docs.subsquid.io/evm-indexing/configuration/evm-logs/
https://docs.subsquid.io/evm-indexing/factory-contracts/
