### ISSUE TITLE
ctx._chain.runtime undefined when processing new incoming block

### ISSUE THREAD

**Issue by jasl** [subsquid/squid-sdk#192]
**Describe the bug**

When processing the newest block, `ctx._chain.runtime` and `ctx._chain.prevRuntime` become `undefined` which will make decoding events (`e.isV1020` and `e.asV1020`) fail by `TypeError: Cannot read properties of undefined (reading 'getEventTypeHash')`.

**To Reproduce**

- Use https://github.com/subsquid/squid-sdk/tree/master/test/balances
  - Update https://github.com/subsquid/squid-sdk/blob/master/test/balances/src/processor.ts#L19 to the latest block to reduce wait time
  - Add `console.log(ctx)` around https://github.com/subsquid/squid-sdk/blob/master/test/balances/src/processor.ts#L23
  - `make up`
  - `make typegen`
  - `make codegen`
  - `npm run build`
  - `make migrate`
- Run the squid by `make process`

After a few minutes, the squid started following the new incoming block. You shall see
```
16:36:40 INFO  sqd:processor 19041243 / 19041243, rate: 2 blocks/sec, mapping: 272 blocks/sec, 10755 items/sec, eta: 0s
{
  _chain: Chain {
    getRpc: [Function (anonymous)],
    blockRange: { from: 19041244, to: 19041244 },
    runtime: undefined,
    prevRuntime: undefined
  },
  log: Logger {
    sink: [Function: prettyStderrSink],
    ns: 'sqd:processor:mapping',
    attributes: undefined
  },
  store: Store { em: [Function (anonymous)], changes: undefined },
  blocks: [
    Block {
      extrinsics: [],
      calls: [],
      events: [Array],
      id: '0019041244-d44ac',
      header: [Object]
    }
  ],
  isHead: false
}
16:36:44 FATAL sqd:processor TypeError: Cannot read properties of undefined (reading 'getEventTypeHash')
                                 at get isV1020 [as isV1020] (/Users/jasl/tmp/balances/lib/types/events.js:18:29)
                                 at /Users/jasl/tmp/balances/lib/processor.js:51:23
                                 at SubstrateBatchProcessor.processBatch (/Users/jasl/tmp/balances/node_modules/@subsquid/substrate-processor/lib/processor.js:264:16)
                                 at Object.process (/Users/jasl/tmp/balances/node_modules/@subsquid/substrate-processor/lib/processor.js:293:41)
                                 at /Users/jasl/tmp/balances/node_modules/@subsquid/util-internal-processor-tools/lib/runner.js:172:40
                                 at /Users/jasl/tmp/balances/node_modules/@subsquid/typeorm-store/lib/database.js:109:52
                                 at TypeormDatabase.performUpdates (/Users/jasl/tmp/balances/node_modules/@subsquid/typeorm-store/lib/database.js:139:19)
                                 at /Users/jasl/tmp/balances/node_modules/@subsquid/typeorm-store/lib/database.js:109:28
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async EntityManager.transaction (/Users/jasl/tmp/balances/node_modules/typeorm/entity-manager/EntityManager.js:73:28)
```

**Expected behavior**

`runtime` and `prevRuntime` should never `undefined`

**Comment by jasl** [comment]
@eldargab can you make a release for the patch?

**Comment by jasl** [comment]
> I've made a release, but note, that until it is not tagged as `latest` - it's even not an `alpha`...

Thank you, I've updated and works fine.
I just saw ArrowSquid is out and I wanna try on a new early-stage project so I can avoid migration when ArrowSquid is officially released.

Do you have ETA for the official release?

**Comment by eldargab** [comment]
Working hard to complete in a couple of weeks.
