### ISSUE TITLE
RpcProtocolError: Response for a batch request should be an array

### ISSUE THREAD

**Issue by bauti-defi** [subsquid/squid-sdk#205]
I reported this bug on discord. Link to conversation for reference here: https://discord.com/channels/857105545135390731/1161650418900799538

**Describe the bug**
Hello, I am indexing uniswap V3 on aribtrum using ankr rpc provider for real-time block indexing. Here is the squid source: https://github.com/bauti-defi/UniswapV3-Indexer

And here is the error i get whenever the squid starts using RPC blockchain data...

```
Starting Arbitrum squid
10:02:01 INFO  sqd:processor last processed final block was 139436154
10:02:01 INFO  sqd:processor processing blocks from 139436155
10:02:01 INFO  sqd:processor using chain RPC data source
10:02:02 INFO  sqd:processor prometheus metrics are served at port 56565
10:02:04 FATAL sqd:processor RpcProtocolError: Response for a batch request should be an array
                                 at HttpConnection.batchCall (/Users/bautista/Desktop/DAMMcap/uni-v3-squid/node_modules/@subsquid/rpc-client/lib/transport/http.js:44:19)
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 code: 1008
```

**To Reproduce**
Pull the uniswap v3 indexer repo. Read the README instructions for starting the arbitrum indexer. Wait till real-time hot block indexing starts... The bug should occur sooner than later.

**Expected behavior**
The squid sdk rpc client should handle the rpc provider error gracefully => retry request.

**Environment (please complete the following information):**
Package json can be found in the repo linked above. Running on macOS Ventura 13.1

**Additional context**
Using https://rpc.ankr.com/arbitrum. Also tested with a premium ankr rpc url but same result. Doesn't happen with ethereum mainnet.

Went into the @Subsquid/rpc-client package to investigate the bug further. 

Inserting a console log of console.log(res) at this line: https://github.com/subsquid/squid-sdk/blob/master/util/rpc-client/src/transport/http.ts#L49

gives the following print out at error time
```
{
  jsonrpc: '2.0',
  error: { code: 0, message: "we can't execute this request" },
  id: null
}
```
it seems that the http client does not handle errors inside the jsonrpc response. not even to bubble them up.

This rpc provider error is related: https://stackoverflow.com/questions/74980274/invalid-batchswap-transaction-in-arbitrum-mainnet

but the real problem here is that the http client is not correctly handling responses that return with error prop

**Comment by eldargab** [comment]
Please, report this error to Ankr.

First, nothing in response suggests, that the error can be retried.

Second, as per [JSON-RPC spec](https://www.jsonrpc.org/specification#batch) 

> The Server should respond with an Array containing the corresponding Response objects, after all of the batch Request objects have been processed.

Although, the spec is vague, and one can argue about what is valid and what is not, at least [go-ethereum rpc client](https://github.com/ethereum/go-ethereum/blob/509a64ffb9405942396276ae111d06f9bded9221/rpc/http.go#L197) and [ethers](https://github.com/ethers-io/ethers.js/blob/e454afb2fa3612c273a09b154c36b35fafab17b1/src.ts/providers/provider-jsonrpc.ts#L516) will treat the response to be simply invalid (as we do).

**Comment by eldargab** [comment]
I don't see, how I can help here.

Please, try other RPC providers. Internally we mostly use https://blastapi.io and never had such problems. Alchemy (allows to efficiently fetch tx receipts) is also good, I believe.

**Comment by bauti-defi** [comment]
Thank you for the tip! I will investigate further. Considering using patch-package to write some error handling into the subsquid rpc client.
