### ISSUE TITLE
Hardcoded RPC retry schedule should be dynamic 

### ISSUE THREAD

**Issue by bauti-defi** [subsquid/squid-sdk#208]
Hello, as of right now the rpc retry schedule is hardcoded. 

```
constructor(options: RpcClientOptions) {
        this.url = trimCredentials(options.url)
        this.con = this.createConnection(options.url)
        this.maxBatchCallSize = options.maxBatchCallSize ?? Number.MAX_SAFE_INTEGER
        this.capacity = options.capacity ?? 10
        this.requestTimeout = options.requestTimeout ?? 0
        this.retryAttempts = options.retryAttempts ?? 0
        this.retrySchedule = options.retrySchedule ?? [10, 100, 500, 2000, 10000, 20000] // HERE!

     // .....
    }
```

I would like to incorporate this option into the RpcChain config so it can be dynamically set. I am willing to fork the repo, implement the change and open up a PR to be merged in. Would the team be interested in this?

**Comment by eldargab** [comment]
Not really...

**Comment by eldargab** [comment]
Alright, allowing `retrySchedule(attempt: number, reason: Error): number` will not harm, I guess...

**Comment by bauti-defi** [comment]
I will implement this soon and submit PR. Please keep this open, thank you @eldargab
