### ISSUE TITLE
Replace ethers.js for data decoding

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/squid-sdk#219]
Scope: 

- #235 -  2-3 days 
- #236 - 1.5 days
- #237 - 1.5 days
- #238 - 1 day
- #242 - 3d

Alternatives:
- Viem
- Custom library optimised for data decoding

**Comment by 2ndshadow** [comment]
Idea: develop extendable framework. Codegen with plugins

**Comment by vanruch** [comment]
- Replace ethers.js interface with abitype ABIs: 2-3 days
- Create custom decoder: 1.5 days
- Benchark, compare with ethers & viem: 1.5 days
- Test with different ABIs: 1 day
