### ISSUE TITLE
Testing framework: RnD

### ISSUE THREAD

**Issue by 2ndshadow** [subsquid/squid-sdk#239]
Epic: Testing framework for squids #220
Estimate: 2d

**Comment by vanruch** [comment]
## Mock data sinks

### Mock TypeORM store
 Use in-memory sqlite data source (outdated example [here](https://gist.github.com/Ciantic/be6a8b8ca27ee15e2223f642b5e01549))

### Mock Filestore
Do we need it? Devs can just delete files manually after testing

### Mock bigquery
I haven't found an easy solution to mock BigQuery. I think best solution here would be to recommend users to use something like https://github.com/goccy/bigquery-emulator and connect to it

## Mock Batch Processors

MockEvmBatchProcessor gets EvmProcessor instance and only cares for what was set in `.addLog`, `.addTransaction`, `.addStateDiff`, `.addTrace` & `.setFields` calls

```ts
import {handler, processor} from "./src"
import {encodeLog} from "@subsquid/evm-utils"
import * as contract from "./abi/contract.ts"

const tokenAddress = '0x12313123...'

test("Correctly calculates minted amounts", () => {
  const mockProcessor = new MockEvmBatchProcessor(processor)
  const db = new MockTypeOrm()
  
  mockProcessor.run(db, handler)
    
  // This would wait until handler(ctx) is called
  await mockProcessor.inject([{
	logs: [
	  encodeLog(contract.events.Mint, tokenAddress, {
	    to: ...
	    amount: 10n
	   }),
       encodeLog(contract.events.Mint, tokenAddress, {
	    to: ...
        amount: 100n
	   }),
	 ],
	}])

  expect((await db.get(Token, tokenAddress)).totalSupply).toBe(110n)
})
```

Similar one for substrate

**Comment by dzhelezov** [comment]
Can we generate events from the ABI?

**Comment by dzhelezov** [comment]
also not clear how `db.get()` works

**Comment by mo4islona** [comment]
> also not clear how db.get() works
Why we can't use a real database?
