### ISSUE TITLE
Make openreader compatible to The Graph

### ISSUE THREAD

**Issue by 2ndshadow** [subsquid/squid-sdk#302]
est. ~4

The things that should be compatible:

- limit, offset vs skip in pagination
- sorting (asc, desc)
- pluralization
- XXXXById****

**Comment by belopash** [comment]
@abernatskiy please test

**Comment by belopash** [comment]
@abernatskiy please test

**Comment by belopash** [comment]
Not supported:
Interfaces
Meta query
Block history
