### ISSUE TITLE
Metadata explorer starting block or a minimal spec version parameter

### ISSUE THREAD

**Issue by khssnv** [subsquid/squid-sdk#328]
Please add `substrate-metadata-explorer` CLI parameter to specify a starting block (or a block range) or a minimal spec version. It can help when we don't want to extract all the versions. For instance on a runtime upgrade which requires to extract only the very last metadata, or in a case when we start indexing from a certain non-zero block and don't need older metadata.

**Comment by belopash** [comment]
New option `--fromBlock` should be available in `@subsquid/substrate-metadata-explorer@3.2.0`
