### ISSUE TITLE
Decode extrinsic error at ingestion

### ISSUE THREAD

**Issue by XY-Wang** [subsquid/squid-sdk#76]
Hi guys,

For the moment an extrinsic module error is coming in the form 
```json
{
  "__kind": "Module",
  "value": {
    "error": "0x06000000",
    "index": 9
  }
}
```

Unfortunately, this is not very helpful when we try to show it in the UI of an explorer. It would be nice to have it in the decoded form like what @polkadotjs/api `api.registry.findMetaError` returns:
```javascript
{
  args: [],
  docs: [ 'Contract trapped during execution.' ],
  fields: Type(0) [ registry: TypeRegistry {}, initialU8aLength: 1 ],
  index: 11,
  method: 'ContractTrapped',
  name: 'ContractTrapped',
  section: 'contracts'
}
```
Is this something you guys plan on supporting?

**Comment by dzhelezov** [comment]
Hey! It's likely not feasible to support on the archive explorer side as it simply presents the raw data saved by the ingester. I recommend setting up a separate squid for these purposes and then decode the error using
```
(ctx._chain as any).scaleCodec.decodeBinary(...)
```
Take a look at this squid to get an idea of how to handle events and extrinsic at the squid side
https://github.com/subsquid/talisman-squidtest/tree/firesquid-migration

**Comment by XY-Wang** [comment]
Hey, thanks for the explanation!

There's no problem subscribing directly to succeeded and failed extrinsics in the squid but the error returned is still not decoded. Is it possible to expose a method like `ctx._chain.decodeError()` similar to `ctx._chain.decodeCall()` that could be used in the squid processor to get the decoded error? If I understood well from this article: https://wiki.polkadot.network/docs/maintain-errors#polkascan-and-subscan, the index 9 in my example above indicates the index of the pallet as described in the chain metadata and the error `0x06000000` indicates the index of the error in the `error` field of the pallet description. Since the squid archive explorer already has the chain metadata, it should be relatively easy to resolve the error?

**Comment by XY-Wang** [comment]
We'll look into supporting this on our end so I'll close the issue.
